<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <Version>0.2.4</Version>
    <AssemblyVersion>0.2.4.0</AssemblyVersion>
    <FileVersion>0.2.4.0</FileVersion>
    <InformationalVersion>0.2.4</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Update="wwwroot\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Selenium.Support" Version="4.26.1" />
    <PackageReference Include="Selenium.WebDriver" Version="4.26.1" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="147.0.7727.11700" />
    <PackageReference Include="Selenium.WebDriver.GeckoDriver" Version="0.36.0" />
    <PackageReference Include="Selenium.WebDriver.MSEdgeDriver" Version="147.0.3912.60" />
  </ItemGroup>
</Project>
